apiVersion: v1
kind: Service
metadata:
  name: java-service
  labels:
    app: java
spec:
  type: NodePort
  selector:
    app: java
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090